spring.application.name=anhduc
server.port=8080

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/iot_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# MQTT Configuration
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=anhduc_iot_backend
mqtt.username=maianhduc
mqtt.password=b23dccn172
mqtt.topic.sensor-data=sensor_data
mqtt.topic.device-control=device_control
mqtt.topic.device-response=device_response

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
